# -*- python -*-

import lsst.sconsUtils
import glob
import os

# scons steals our environment away, so we have to reinstate it
env = lsst.sconsUtils.env.Clone()
for name in ("PYTHONPATH", "LD_LIBRARY_PATH",
             "DYLD_LIBRARY_PATH", "PATH"):
    if name in os.environ:
        env.AppendENVPath(name, os.environ[name])

# we may need an explicit library load path specified in the command
libpathstr = lsst.sconsUtils.utils.libraryLoaderEnvironment()

# We always run these commands with an explicit python rather than relying on the shebang
python = "{} python".format(libpathstr)

for camera in ["auxTel", "lsstCam", "imsim", "phosim", "ts8e2v", "ts8itl", "ucd"]:
    # Invoke the bin.src variant so that we do not depend on the shebang
    # target having been run
    commandInst = env.Command("%s.yaml" % camera, "",
                              "%s bin.src/generateCamera.py --path %s:lsstCam:. $TARGET" %
                              (python, camera))

    env.Depends(commandInst, lsst.sconsUtils.targets["python"])
    dirList = ["lsstCam"]
    if os.path.isdir(camera):
        dirList.append(camera)

    for d in dirList:
        for f in glob.glob(os.path.join(d, "*.yaml")):
            env.Depends(commandInst, f)

    for f in ["cameraHeader.yaml", "cameraTransforms.yaml", "rafts.yaml", env.Glob("R??.yaml")]:
        env.Depends(commandInst, f)
