# This file is part of obs_lsst.
#
# Developed for the LSST Data Management System.
# This product includes software developed by the LSST Project
# (http://www.lsst.org).
# See the COPYRIGHT file at the top-level directory of this distribution
# for details of code ownership.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import os.path
import unittest
import warnings
import astropy.time
import astropy.units as u
import astropy.units.cds as cds
from astropy.io.fits.verify import VerifyWarning

import lsst.obs.lsst.translators  # noqa: F401 -- register the translators
from astro_metadata_translator.tests import MetadataAssertHelper

TESTDIR = os.path.abspath(os.path.dirname(__file__))


class LsstMetadataTranslatorTestCase(unittest.TestCase, MetadataAssertHelper):
    """Each test reads in raw headers from YAML files, constructs an
    `ObservationInfo`, and compares the properties with the expected values
    defined in the corresponding `dict`."""

    datadir = os.path.join(TESTDIR, "headers")

    def test_lsstCam_translator(self):
        test_data = (("lsstCam-MC_C_20190319_000001_R10_S02.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=0.0*u.s,
                           detector_exposure_id=0x269200011d,
                           detector_group="R10",
                           detector_name="S02",
                           detector_num=29,
                           detector_serial="ITL-3800C-041",
                           exposure_id=3019031900001,
                           exposure_group="3019031900001",
                           exposure_time=0.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=1,
                           group_counter_start=1,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=1,
                           observation_id="MC_C_20190319_000001",
                           observation_type="bias",
                           observation_reason="bias",
                           observing_day=20190319,
                           observing_day_offset=astropy.time.TimeDelta(25200.0, scale="tai", format="sec"),
                           physical_filter="unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=3019031900001)),
                     ("lsstCam-MC_C_20190319_000001_R22_S21.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=0.0*u.s,
                           detector_exposure_id=0x2692000161,
                           detector_group="R22",
                           detector_name="S21",
                           detector_num=97,
                           detector_serial="ITL-3800C-139",
                           exposure_id=3019031900001,
                           exposure_group="3019031900001",
                           exposure_time=0.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=1,
                           group_counter_start=1,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=1,
                           observation_id="MC_C_20190319_000001",
                           observation_type="bias",
                           observation_reason="bias",
                           observing_day=20190319,
                           observing_day_offset=astropy.time.TimeDelta(25200.0, scale="tai", format="sec"),
                           physical_filter="unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=3019031900001)),
                     ("lsstCam-MC_C_20190322_000002_R10_S22.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam",
                           boresight_rotation_coord="unknown",
                           can_see_sky=None,
                           dark_time=1.0*u.s,
                           detector_exposure_id=0x2693800223,
                           detector_group="R10",
                           detector_name="S22",
                           detector_num=35,
                           detector_serial="ITL-3800C-103",
                           exposure_id=3019032200002,
                           exposure_group="3019032200002",
                           exposure_time=1.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=2,
                           group_counter_start=2,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=2,
                           observation_id="MC_C_20190322_000002",
                           observation_type="flat",
                           observation_reason="flat",
                           observing_day=20190322,
                           observing_day_offset=astropy.time.TimeDelta(25200.0, scale="tai", format="sec"),
                           physical_filter="SDSSi~ND_OD0.5",
                           pressure=None,
                           relative_humidity=None,
                           science_program="6489D",
                           temperature=None,
                           visit_id=3019032200002)),
                     ("lsstCam-MC_C_20190406_000643_R10_S00.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam",
                           boresight_rotation_coord="unknown",
                           can_see_sky=None,
                           dark_time=1007.422*u.s,
                           detector_exposure_id=0x269b02831b,
                           detector_group="R10",
                           detector_name="S00",
                           detector_num=27,
                           detector_serial="ITL-3800C-145",
                           exposure_id=3019040600643,
                           exposure_group="3019040600643",
                           exposure_time=999.99*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=643,
                           group_counter_start=643,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=643,
                           observation_id="MC_C_20190406_000643",
                           observation_type="flat",
                           observation_reason="lambda",
                           observing_day=20190406,
                           observing_day_offset=astropy.time.TimeDelta(25200.0, scale="tai", format="sec"),
                           physical_filter="950nm",
                           pressure=None,
                           relative_humidity=None,
                           science_program="6549D",
                           temperature=None,
                           visit_id=3019040600643)),
                     ("lsstCam-faked-future-ccs.yaml",  # Old CCS observation with date in future for exp_id
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=0.0*u.s,
                           detector_exposure_id=0xdb480011d,
                           detector_group="R10",
                           detector_name="S02",
                           detector_num=29,
                           detector_serial="ITL-3800C-041",
                           exposure_id=2029031900001,
                           exposure_group="2029031900001",
                           exposure_time=0.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=1,
                           group_counter_start=1,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=1,
                           observation_id="MC_C_20190319_000001",
                           observation_type="bias",
                           observation_reason="bias",
                           observing_day=20290319,
                           observing_day_offset=astropy.time.TimeDelta(25200.0, scale="tai", format="sec"),
                           physical_filter="unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=2029031900001)),
                     ("lsstCam-MC_C_20231107_000078_R01_S01.json",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=0.092*u.s,
                           detector_exposure_id=0x9e1004e01,
                           detector_group="R01",
                           detector_name="S01",
                           detector_num=1,
                           detector_serial="ITL-3800C-226",
                           exposure_id=2023110700078,
                           exposure_group="2023110700078",
                           exposure_time=0.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=78,
                           group_counter_start=78,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=78,
                           observation_id="MC_C_20231107_000078",
                           observation_type="bias",
                           observation_reason="bot_persistence",
                           observing_day=20231107,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="ph_5",
                           pressure=None,
                           relative_humidity=None,
                           science_program="13518",
                           temperature=None,
                           visit_id=2023110700078)),
                     ("lsstCam-MC_O_20250415_000060_R01_S01.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam",
                           boresight_rotation_coord="sky",
                           boresight_rotation_angle=-43.62470328866432*u.deg,
                           can_see_sky=True,
                           dark_time=15.9548*u.s,
                           detector_exposure_id=0xae7803c01,
                           detector_group="R01",
                           detector_name="S01",
                           detector_num=1,
                           detector_serial="ITL-3800C-226",
                           exposure_id=2025041500060,
                           exposure_group="2025-04-16T00:53:10.143",
                           exposure_time=15.0*u.s,
                           focus_z=-2.856403126427015*u.mm,
                           group_counter_end=60,
                           group_counter_start=60,
                           has_simulated_content=False,
                           object="Vela_SNR",
                           observation_counter=60,
                           observation_id="MC_O_20250415_000060",
                           observation_type="acq",
                           observation_reason="first_focus",
                           observing_day=20250415,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="i_39",
                           pressure=74390.0*u.Pa,
                           relative_humidity=33.400001525878906,
                           science_program="BLOCK-T434",
                           temperature=11.024999618530273*u.deg_C,
                           visit_id=3246943901430000)),
                     )
        for filename, expected in test_data:
            with self.subTest(f"Testing {filename}"):
                self.assertObservationInfoFromYaml(filename, dir=self.datadir, **expected)

    def test_phoSimLsstCam_translator(self):
        test_data = (("lsstCam-MC_H_20100217_000032_R22_S00.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           dark_time=15.0*u.s,
                           detector_exposure_id=0x401780205a,
                           detector_group="R22",
                           detector_name="S00",
                           detector_num=90,
                           detector_serial="E2V-CCD250-369",
                           detector_unique_name="R22_S00",
                           exposure_group="4010021700032",
                           exposure_id=4010021700032,
                           exposure_time=15.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=32,
                           group_counter_start=32,
                           has_simulated_content=True,
                           object="UNKNOWN",
                           observation_counter=32,
                           observation_id="MC_H_20100217_000032",
                           observation_reason="phosim",
                           observation_type="science",
                           observing_day=20100217,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="g",
                           pressure=None,
                           relative_humidity=None,
                           science_program="9006001",
                           temperature=None,
                           visit_id=4010021700032)),
                     )
        for filename, expected in test_data:
            with self.subTest(f"Testing {filename}"):
                self.assertObservationInfoFromYaml(filename, dir=self.datadir,
                                                   check_wcs=False, **expected)

    def test_lsstCamSim_translator(self):
        test_data = (("lsstCamSim-MC_S_20240321_000720_R22_S11.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCamSim",
                           boresight_rotation_coord="sky",
                           boresight_rotation_angle=81.12326734428959 * u.deg,
                           can_see_sky=True,
                           dark_time=30.0*u.s,
                           detector_exposure_id=730756993118,
                           detector_group="R22",
                           detector_name="S11",
                           detector_num=94,
                           detector_serial="E2V-CCD250-382",
                           detector_unique_name="R22_S11",
                           exposure_group="7024032100720",
                           exposure_id=7024032100720,
                           exposure_time=30.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=720,
                           group_counter_start=720,
                           has_simulated_content=True,
                           object="UNKNOWN",
                           observation_counter=720,
                           observation_id="MC_S_20240321_000720",
                           observation_reason="survey",
                           observation_type="science",
                           observing_day=20240321,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="r_57",
                           pressure=None,
                           relative_humidity=None,
                           science_program="720",
                           temperature=None,
                           visit_id=7024032100720)),
                     )
        for filename, expected in test_data:
            with self.subTest(f"Testing {filename}"):
                self.assertObservationInfoFromYaml(filename, dir=self.datadir,
                                                   check_wcs=False, **expected)

    def test_comCam_translator(self):
        test_data = (("comCam-CC_C_20190530_000001_R22_S00.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTComCam",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=0.398*u.s,
                           detector_exposure_id=0x26b6000100,
                           detector_group="R22",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-229",
                           exposure_id=3019053000001,
                           exposure_group="3019053000001",
                           exposure_time=0.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=1,
                           group_counter_start=1,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=1,
                           observation_id="CC_C_20190530_000001",
                           observation_type="bias",
                           observation_reason="bias",
                           observing_day=20190530,
                           observing_day_offset=astropy.time.TimeDelta(25200.0, scale="tai", format="sec"),
                           physical_filter="unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=3019053000001)),
                     ("comCam-CC_C_20190526_000223_R22_S01.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTComCam",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=0.034*u.s,
                           detector_exposure_id=0x26b400df01,
                           detector_group="R22",
                           detector_name="S01",
                           detector_num=1,
                           detector_serial="ITL-3800C-251",
                           exposure_id=3019052600223,
                           exposure_group="3019052600223",
                           exposure_time=0.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=223,
                           group_counter_start=223,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=223,
                           observation_id="CC_C_20190526_000223",
                           observation_type="bias",
                           observation_reason="dark",
                           observing_day=20190526,
                           observing_day_offset=astropy.time.TimeDelta(25200.0, scale="tai", format="sec"),
                           physical_filter="unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=3019052600223)),
                     ("comCam-CC_O_20241108_000266_R22_S00.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTComCam",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           boresight_rotation_angle=102.79926387330579 * u.deg,
                           wcs_params=dict(max_sep=2.5),
                           dark_time=30.4306*u.s,
                           detector_exposure_id=45508266496,
                           detector_group="R22",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-229",
                           exposure_id=2024110800266,
                           exposure_group="2024-11-09T06:33:55.311",
                           exposure_time=30.0*u.s,
                           focus_z=2.0585230644024572*u.mm,
                           group_counter_end=266,
                           group_counter_start=266,
                           has_simulated_content=False,
                           object="slew_icrs",
                           observation_counter=266,
                           observation_id="CC_O_20241108_000266",
                           observation_type="science",
                           observation_reason="science",
                           observing_day=20241108,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="g_01",
                           pressure=74120.0 * u.Pa,
                           relative_humidity=22.299999237060547,
                           science_program="PP-SURVEY",
                           temperature=13.725000381469727 * u.deg_C,
                           visit_id=3110636353110000)),
                     )
        for filename, expected in test_data:
            with self.subTest(f"Testing {filename}"):
                self.assertObservationInfoFromYaml(filename, dir=self.datadir, **expected)

    def test_comCamSim_translator(self):
        test_data = (("comCamSim-IM_P_20240117_000000_R22_S00.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTComCamSim",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=0.0*u.s,
                           detector_group="R22",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-229",
                           exposure_id=5024011700000,
                           exposure_group="5024011700000",
                           exposure_time=0.0*u.s,
                           focus_z=0.0 * u.mm,
                           group_counter_end=5024011700000,
                           group_counter_start=5024011700000,
                           has_simulated_content=True,
                           object="UNKNOWN",
                           observation_counter=0,
                           observation_id="IM_P_20240117_000000",
                           observation_type="bias",
                           observation_reason="calibration",
                           observing_day=20240117,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="r_03",
                           pressure=None,
                           relative_humidity=None,
                           science_program="calibration",
                           temperature=None,
                           visit_id=5024011700000,
                           )),
                     ("comCamSim-CC_S_20240321_000093_R22_S22.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTComCamSim",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           dark_time=33.0546 * u.s,
                           detector_group="R22",
                           detector_name="S22",
                           detector_num=8,
                           detector_serial="ITL-3800C-206",
                           exposure_id=2026032100093,
                           exposure_group="2024-03-22T03:41:54.994",
                           exposure_time=30.0 * u.s,
                           focus_z=0.0 * u.mm,
                           group_counter_end=93,
                           group_counter_start=93,
                           has_simulated_content=True,
                           object="TEST",
                           observation_counter=93,
                           observation_id="CC_S_20260321_000093",
                           observation_type="science",
                           observation_reason="object",
                           observing_day=20260321,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="r_03",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=2910085149940000,
                           )),
                     )
        for filename, expected in test_data:
            with self.subTest(f"Testing {filename}"):
                self.assertObservationInfoFromYaml(
                    filename, dir=self.datadir, check_wcs=False, **expected
                )

    def test_phoSimComCam_translator(self):
        test_data = (("comCam-CC_H_20100217_006001_R22_S00.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTComCam",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           dark_time=1.0*u.s,
                           detector_exposure_id=0x4017977100,
                           detector_group="R22",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-229",
                           exposure_id=4010021706001,
                           exposure_group="4010021706001",
                           exposure_time=1.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=6001,
                           group_counter_start=6001,
                           has_simulated_content=True,
                           object="UNKNOWN",
                           observation_counter=6001,
                           observation_id="CC_H_20100217_006001",
                           observation_type="science",
                           observation_reason="test",
                           observing_day=20100217,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="g_01",
                           pressure=None,
                           relative_humidity=None,
                           science_program="9006001",
                           temperature=None,
                           visit_id=4010021706001)),
                     )
        for filename, expected in test_data:
            with self.subTest(f"Testing {filename}"):
                self.assertObservationInfoFromYaml(filename, dir=self.datadir,
                                                   check_wcs=False, **expected)

    def test_phosim_translator(self):
        test_data = (("phosim-lsst_a_204595_f3_R11_S02_E000.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam-PhoSim",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           dark_time=30.0*u.s,
                           detector_exposure_id=204595038,
                           detector_group="R11",
                           detector_name="S02",
                           detector_num=38,
                           detector_serial="R11_S02",
                           exposure_id=204595,
                           exposure_group="204595",
                           exposure_time=30.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=204595,
                           group_counter_start=204595,
                           has_simulated_content=True,
                           object="UNKNOWN",
                           observation_counter=0,
                           observation_id="204595",
                           observation_type="science",
                           observation_reason="phosim",
                           observing_day=20221005,
                           observing_day_offset=astropy.time.TimeDelta(0.0, scale="tai", format="sec"),
                           physical_filter="i",
                           pressure=520.0*cds.mmHg,
                           relative_humidity=40.0,
                           science_program="204595",
                           temperature=20.0*u.deg_C,
                           visit_id=204595,
                           wcs_params=dict(max_sep=3000.))),  # 2022
                     )
        for filename, expected in test_data:
            with self.subTest(f"Testing {filename}"):
                with warnings.catch_warnings():
                    # Avoid warnings from too-long FITS header keys.
                    warnings.simplefilter("ignore", VerifyWarning)
                    self.assertObservationInfoFromYaml(filename, dir=self.datadir, **expected)

    def test_latiss_translator(self):
        test_data = (("latiss-2018-09-20-05700065-det000.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="unknown",
                           can_see_sky=None,
                           dark_time=27.0*u.s,
                           detector_exposure_id=0x2638004100,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-098",
                           exposure_id=3018092000065,
                           exposure_group="3018092000065",
                           exposure_time=27.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=65,
                           group_counter_start=65,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=65,
                           observation_id="AT_C_20180920_000065",
                           observation_type="unknown",
                           observation_reason="unknown",
                           observing_day=20180920,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="unknown~unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=3018092000065,
                           )),
                     ("latiss-AT_O_20190306_000014.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="unknown",
                           can_see_sky=None,
                           dark_time=1.06*u.s,
                           detector_exposure_id=0x68b800e00,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-098",
                           exposure_id=2019030600014,
                           exposure_group="2019030600014",
                           exposure_time=1.06*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=14,
                           group_counter_start=14,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=14,
                           observation_id="AT_O_20190306_000014",
                           observation_type="unknown",
                           observation_reason="unknown",
                           observing_day=20190306,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="unknown~unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=2019030600014,
                           )),
                     ("latiss-AT_O_20190329_000022-ats-wfs_ccd.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=0.0*u.s,
                           detector_exposure_id=0x697001600,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-098",
                           exposure_id=2019032900022,
                           exposure_group="2019032900022",
                           exposure_time=0.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=22,
                           group_counter_start=22,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=22,
                           observation_id="AT_O_20190329_000022",
                           observation_type="bias",
                           observation_reason="unknown",
                           observing_day=20190329,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="unknown~unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=2019032900022,
                           )),
                     ("latiss-future.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=0.0*u.s,
                           detector_exposure_id=0x74e001600,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2020032900022,
                           exposure_group="2020-03-29T16:55:00.012#24",
                           exposure_time=0.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=22,
                           group_counter_start=22,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=22,
                           observation_id="AT_X_20200329_000022",
                           observation_type="bias",
                           observation_reason="unknown",
                           observing_day=20200329,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="unknown~unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=1654305000120024,
                           )),
                     ("latiss-AT_O_20190915_000037.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=0.0*u.s,
                           detector_exposure_id=0x6ec002500,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2019091500037,
                           exposure_group="bias_0027_0100",
                           exposure_time=0.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=37,
                           group_counter_start=37,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=37,
                           observation_id="AT_O_20190915_000037",
                           observation_type="bias",
                           observation_reason="unknown",
                           observing_day=20190915,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="unknown~unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=3575576933793566714,
                           )),
                     ("latiss-AT_O_20191031_000004.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="unknown",
                           can_see_sky=None,
                           dark_time=3.0*u.s,
                           detector_exposure_id=0x703000400,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2019103100004,
                           exposure_group="TEST01",
                           exposure_time=3.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=4,
                           group_counter_start=4,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=4,
                           observation_id="AT_O_20191031_000004",
                           observation_type="engtest",
                           observation_reason="unknown",
                           observing_day=20191031,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="unknown~unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=1123819875881954006,
                           )),
                     ("latiss-AT_O_20191104_000003.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="unknown",
                           can_see_sky=None,
                           dark_time=3.0*u.s,
                           detector_exposure_id=0x705000300,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2019110400003,
                           exposure_group="TEST01",
                           exposure_time=3.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=3,
                           group_counter_start=3,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=3,
                           observation_id="AT_O_20191104_000003",
                           observation_type="engtest",
                           observation_reason="unknown",
                           observing_day=20191104,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="unknown~unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=1123819875881954006,
                           )),
                     ("latiss-AT_O_20191113_000061.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="unknown",
                           can_see_sky=None,
                           dark_time=0.5*u.s,
                           detector_exposure_id=0x709803d00,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2019111300061,
                           exposure_group="wave,Focus,455,32.0PH=5um",
                           exposure_time=0.5*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=61,
                           group_counter_start=61,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=61,
                           observation_id="AT_O_20191113_000061",
                           observation_type="engtest",
                           observation_reason="unknown",
                           observing_day=20191113,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="empty~ronchi90lpmm",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=1892608703001301325,
                           )),
                     ("latiss-AT_O_20191118_000011.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=15.0*u.s,
                           detector_exposure_id=0x70c000b00,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2019111800011,
                           exposure_group="dark_0002_0005",
                           exposure_time=15.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=11,
                           group_counter_start=11,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=11,
                           observation_id="AT_O_20191118_000011",
                           observation_type="dark",
                           observation_reason="unknown",
                           observing_day=20191118,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="diffuser~ronchi170lpmm",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=6861884254113212214,
                           )),
                     ("latiss-AT_O_20200121_000045.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="sky",
                           can_see_sky=None,
                           dark_time=100.0*u.s,
                           detector_exposure_id=0x72c002d00,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2020012100045,
                           exposure_group="test",
                           exposure_time=100.0*u.s,
                           focus_z=0.560002659202*u.mm,
                           group_counter_end=45,
                           group_counter_start=45,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=45,
                           observation_id="AT_O_20200121_000045",
                           observation_type="engtest",
                           observation_reason="unknown",
                           observing_day=20200121,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="blank_bk7_wg05~empty",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=4702443654717948604,
                           check_altaz=True,
                           )),
                     ("latiss-AT_O_20200128_000379.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           dark_time=5.0*u.s,
                           detector_exposure_id=0x72f817b00,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2020012800379,
                           exposure_group="2020-01-29T07:25:52.166",
                           exposure_time=5.0*u.s,
                           focus_z=0.35416568455*u.mm,
                           group_counter_end=379,
                           group_counter_start=379,
                           has_simulated_content=False,
                           object="HD107696",
                           observation_counter=379,
                           observation_id="AT_O_20200128_000379",
                           observation_type="science",
                           observation_reason="science",
                           observing_day=20200128,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="KPNO_406_828nm~empty",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=1602123521660000,
                           # We have some timing discrepancies in the headers
                           # that make it hard to match the demand RA/DEC to
                           # the recorded AZ/EL/TIME.
                           wcs_params=dict(max_sep=7.),
                           )),
                     ("latiss-AT_O_20220405_000348.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           dark_time=30.3176279067993*u.s,
                           detector_exposure_id=0x8be815c00,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2022040500348,
                           exposure_group="2022-04-06T02:58:07.181",
                           exposure_time=30.0*u.s,
                           focus_z=0.0697081759572029*u.mm,
                           group_counter_end=349,
                           group_counter_start=348,
                           has_simulated_content=False,
                           object="LATISS_E6A_00000040",
                           observation_counter=348,
                           observation_id="AT_O_20220405_000348",
                           observation_type="science",
                           observation_reason="object",
                           observing_day=20220405,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="SDSSr~empty",
                           pressure=744.3*u.hPa,
                           relative_humidity=19.0,
                           science_program="LATISS_E6A",
                           temperature=12.3*u.deg_C,
                           visit_id=2291434871810000,
                           # We have some timing discrepancies in the headers
                           # that make it hard to match the demand RA/DEC to
                           # the recorded AZ/EL/TIME.
                           wcs_params=dict(max_sep=7.),
                           )),
                     ("latiss-AT_O_20220405_000349.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           dark_time=30.2387452125549*u.s,
                           detector_exposure_id=0x8be815d00,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2022040500349,
                           exposure_group="2022-04-06T02:58:07.181",
                           exposure_time=30.0*u.s,
                           focus_z=0.0697081759572029*u.mm,
                           group_counter_end=349,
                           group_counter_start=348,
                           has_simulated_content=False,
                           object="LATISS_E6A_00000040",
                           observation_counter=349,
                           observation_id="AT_O_20220405_000349",
                           observation_type="science",
                           observation_reason="object",
                           observing_day=20220405,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="SDSSr~empty",
                           pressure=744.3*u.hPa,
                           relative_humidity=19.0,
                           science_program="LATISS_E6A",
                           temperature=12.3*u.deg_C,
                           visit_id=2291434871810000,
                           # We have some timing discrepancies in the headers
                           # that make it hard to match the demand RA/DEC to
                           # the recorded AZ/EL/TIME.
                           wcs_params=dict(max_sep=7.),
                           )),
                     ("latiss-AT_C_20220426_000004_R00_S00.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="unknown",
                           can_see_sky=None,
                           dark_time=537.406*u.s,
                           detector_exposure_id=0x28c9000400,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=3022042600004,
                           exposure_group="3022042600004",
                           exposure_time=-1.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=4,
                           group_counter_start=4,
                           has_simulated_content=False,
                           object="UNKNOWN",
                           observation_counter=4,
                           observation_id="AT_C_20220426_000004",
                           observation_type="unknown",
                           observation_reason="unknown",
                           observing_day=20220426,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="unknown~unknown",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=3022042600004,
                           )),
                     ("latiss-AT_O_20230321_000053.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=30.0126*u.s,
                           detector_exposure_id=0x96d803500,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2023032100053,
                           exposure_group="2023-03-21T16:11:07.633",
                           exposure_time=30.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=53,
                           group_counter_start=53,
                           has_simulated_content=False,
                           object="slew_icrs",
                           observation_counter=53,
                           observation_id="AT_O_20230321_000053",
                           observation_type="dark",
                           observation_reason="dark",
                           observing_day=20230321,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="empty~empty",
                           pressure=None,
                           relative_humidity=None,
                           science_program="unknown",
                           temperature=None,
                           visit_id=2593446676330000,
                           check_altaz=True,
                           )),
                     ("latiss-AT_O_20230705_000379_R00_S00.json",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           dark_time=30.2418*u.s,
                           detector_exposure_id=0x9a2817b00,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2023070500379,
                           exposure_group="2023-07-06T04:53:15.609",
                           exposure_time=30.0*u.s,
                           focus_z=-0.008921561762690544*u.mm,
                           group_counter_end=379,
                           group_counter_start=379,
                           has_simulated_content=False,
                           object="HD165763",
                           observation_counter=379,
                           observation_id="AT_O_20230705_000379",
                           observation_type="science",
                           observation_reason="sitcom-857",
                           observing_day=20230705,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="empty~holo4_003",
                           pressure=777.80*u.hPa,
                           relative_humidity=15.149999618530273,
                           science_program="BLOCK-59",
                           temperature=5.775000095367432*u.deg_C,
                           visit_id=2685487956090000,
                           check_altaz=True,
                           )),
                     ("latiss-AT_O_20240624_000106_R00_S00.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           dark_time=30.2407*u.s,
                           detector_exposure_id=44358986240,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2024062400106,
                           exposure_group="2024-06-25T01:26:31.895#1",
                           exposure_time=30.0*u.s,
                           focus_z=0.742219865322113*u.mm,
                           group_counter_end=106,
                           group_counter_start=106,
                           has_simulated_content=False,
                           object="HD 131586",
                           observation_counter=106,
                           observation_id="AT_O_20240624_000106",
                           observation_type="cwfs",
                           observation_reason="intra",
                           observing_day=20240624,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="SDSSr_65mm~empty",
                           pressure=73880*u.Pa,
                           relative_humidity=40.650001525878906,
                           science_program="cwfs",
                           temperature=1.5750000476837158*u.deg_C,
                           visit_id=2992083918950001,
                           check_altaz=True,
                           )),
                     ("latiss-AT_O_20240624_000106_R00_S00-patched.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="sky",
                           can_see_sky=False,
                           dark_time=30.2407*u.s,
                           detector_exposure_id=44358986240,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2024062400106,
                           exposure_group="2024-06-25T01:26:31.895#1",
                           exposure_time=30.0*u.s,
                           focus_z=0.742219865322113*u.mm,
                           group_counter_end=106,
                           group_counter_start=106,
                           has_simulated_content=False,
                           object="HD 131586",
                           observation_counter=106,
                           observation_id="AT_O_20240624_000106",
                           observation_type="science",
                           observation_reason="intra",
                           observing_day=20240624,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="SDSSr_65mm~empty",
                           pressure=73880*u.Pa,
                           relative_humidity=40.650001525878906,
                           science_program="cwfs",
                           temperature=1.5750000476837158*u.deg_C,
                           visit_id=2992083918950001,
                           check_altaz=True,
                           )),
                     ("latiss-AT_O_20240624_000169_R00_S00.yaml",
                      dict(telescope="Rubin Auxiliary Telescope",
                           instrument="LATISS",
                           boresight_rotation_coord="unknown",
                           can_see_sky=False,
                           dark_time=30.0096*u.s,
                           detector_exposure_id=44359002368,
                           detector_group="RXX",
                           detector_name="S00",
                           detector_num=0,
                           detector_serial="ITL-3800C-068",
                           exposure_id=2024062400169,
                           exposure_group="2024-06-25T07:10:40.297",
                           exposure_time=30.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=169,
                           group_counter_start=169,
                           has_simulated_content=False,
                           object="FlatField position",
                           observation_counter=169,
                           observation_id="AT_O_20240624_000169",
                           observation_type="dark",
                           observation_reason="dark",
                           observing_day=20240624,
                           observing_day_offset=astropy.time.TimeDelta(43200.0, scale="tai", format="sec"),
                           physical_filter="SDSSr_65mm~empty",
                           pressure=73760*u.Pa,
                           relative_humidity=44.42499923706055,
                           science_program="unknown",
                           temperature=0.02500000037252903*u.deg_C,
                           visit_id=2992290402970000,
                           check_altaz=True,
                           )),
                     )
        with warnings.catch_warnings():
            # Avoid warnings from too-long FITS header keys.
            warnings.simplefilter("ignore", VerifyWarning)
            self.assertObservationInfoFromYaml("latiss-future.yaml", dir=self.datadir)
            for filename, expected in test_data:
                with self.subTest(f"Testing {filename}"):
                    self.assertObservationInfoFromYaml(filename, dir=self.datadir, **expected)

        # This translation should fail
        with self.assertRaises(KeyError):
            self.assertObservationInfoFromYaml("latiss-future-bad.yaml", dir=self.datadir)

    def test_imsim_translator(self):
        test_data = (("imsim-bias-lsst_a_3010002_R11_S00.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam-imSim",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           dark_time=0.0*u.s,
                           detector_exposure_id=3010002036,
                           detector_group="R11",
                           detector_name="S00",
                           detector_num=36,
                           detector_serial="LCA-11021_RTM-000",
                           exposure_id=3010002,
                           exposure_group="3010002",
                           exposure_time=0.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=3010002,
                           group_counter_start=3010002,
                           has_simulated_content=True,
                           object="UNKNOWN",
                           observation_counter=0,
                           observation_id="3010002",
                           observation_type="science",  # The header is wrong
                           observation_reason="imsim",
                           observing_day=20220101,
                           observing_day_offset=astropy.time.TimeDelta(0.0, scale="tai", format="sec"),
                           physical_filter="i",
                           pressure=None,
                           relative_humidity=40.0,
                           science_program="42",
                           temperature=None,
                           visit_id=3010002,
                           wcs_params=dict(max_sep=3000.),  # 2022
                           )),
                     ("imsim-lsst_a_204595_R11_S02_i.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam-imSim",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           dark_time=30.0*u.s,
                           detector_exposure_id=204595038,
                           detector_group="R11",
                           detector_name="S02",
                           detector_num=38,
                           detector_serial="LCA-11021_RTM-000",
                           exposure_id=204595,
                           exposure_group="204595",
                           exposure_time=30.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=204595,
                           group_counter_start=204595,
                           has_simulated_content=True,
                           object="UNKNOWN",
                           observation_counter=0,
                           observation_id="204595",
                           observation_type="science",  # The header is wrong
                           observation_reason="imsim",
                           observing_day=20221005,
                           observing_day_offset=astropy.time.TimeDelta(0.0, scale="tai", format="sec"),
                           physical_filter="i_sim_1.4",
                           pressure=None,
                           relative_humidity=40.0,
                           science_program="204595",
                           temperature=None,
                           visit_id=204595,
                           wcs_params=dict(max_sep=3000.),  # 2022
                           )),
                     ("imsim-flats-lsst_a_5000007_R11_S20_i.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam-imSim",
                           boresight_rotation_coord="sky",
                           can_see_sky=None,
                           dark_time=30.0*u.s,
                           detector_exposure_id=5000007042,
                           detector_group="R11",
                           detector_name="S20",
                           detector_num=42,
                           detector_serial="LCA-11021_RTM-000",
                           exposure_id=5000007,
                           exposure_group="5000007",
                           exposure_time=30.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=5000007,
                           group_counter_start=5000007,
                           has_simulated_content=True,
                           object="UNKNOWN",
                           observation_counter=0,
                           observation_id="5000007",
                           observation_type="flat",
                           observation_reason="imsim",
                           observing_day=20220806,
                           observing_day_offset=astropy.time.TimeDelta(0.0, scale="tai", format="sec"),
                           physical_filter="i",
                           pressure=None,
                           relative_humidity=40.0,
                           science_program="5000007",
                           temperature=None,
                           visit_id=5000007,
                           wcs_params=dict(max_sep=3000.),  # 2022
                           )),
                     ("imsim-dark-lsst_a_4010003_R11_S11.yaml",
                      dict(telescope="Simonyi Survey Telescope",
                           instrument="LSSTCam-imSim",
                           boresight_rotation_coord="sky",
                           can_see_sky=True,
                           dark_time=500.0*u.s,
                           detector_exposure_id=4010003040,
                           detector_group="R11",
                           detector_name="S11",
                           detector_num=40,
                           detector_serial="LCA-11021_RTM-000",
                           exposure_id=4010003,
                           exposure_group="4010003",
                           exposure_time=500.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=4010003,
                           group_counter_start=4010003,
                           has_simulated_content=True,
                           object="UNKNOWN",
                           observation_counter=0,
                           observation_id="4010003",
                           observation_type="science",  # The header is wrong
                           observation_reason="imsim",
                           observing_day=20220101,
                           observing_day_offset=astropy.time.TimeDelta(0.0, scale="tai", format="sec"),
                           physical_filter="i",
                           pressure=None,
                           relative_humidity=40.0,
                           science_program="42",
                           temperature=None,
                           visit_id=4010003,
                           wcs_params=dict(max_sep=3000.),  # 2022
                           )),
                     )
        for filename, expected in test_data:
            with self.subTest(f"Testing {filename}"):
                self.assertObservationInfoFromYaml(filename, dir=self.datadir, **expected)

    def test_ts3_translator(self):
        test_data = (("ts3-E2V-CCD250-411_lambda_flat_1000_025_20181115075559.yaml",
                      dict(telescope=None,
                           instrument="LSST-TS3",
                           can_see_sky=False,
                           dark_time=44.631*u.s,
                           detector_exposure_id=201811151255111433,
                           detector_group="R433",
                           detector_name="S00",
                           detector_num=433,
                           detector_serial="E2V-CCD250-411",
                           exposure_id=201811151255111,
                           exposure_group="201811151255111",
                           exposure_time=44.631*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=25,
                           group_counter_start=25,
                           has_simulated_content=False,
                           observation_counter=25,
                           observation_id="E2V-CCD250-411_lambda_flat_1000_025_20181115075559",
                           observation_type="flat",
                           observation_reason="lambda",
                           observing_day=20181115,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="550CutOn",
                           science_program="2018-11-15",
                           visit_id=201811151255111)),
                     ("ts3-ITL-3800C-098_lambda_flat_1000_067_20160722020740.yaml",
                      dict(telescope=None,
                           instrument="LSST-TS3",
                           can_see_sky=False,
                           dark_time=30.611*u.s,
                           detector_exposure_id=201607220607067071,
                           detector_group="R071",
                           detector_name="S00",
                           detector_num=71,
                           detector_serial="ITL-3800C-098",
                           exposure_id=201607220607067,
                           exposure_group="201607220607067",
                           exposure_time=30.611*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=67,
                           group_counter_start=67,
                           has_simulated_content=False,
                           observation_counter=67,
                           observation_id="ITL-3800C-098_lambda_flat_1000_067_20160722020740",
                           observation_type="flat",
                           observation_reason="lambda",
                           observing_day=20160721,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="550CutOn",
                           science_program="2016-07-22",
                           visit_id=201607220607067)),
                     )
        for filename, expected in test_data:
            with self.subTest(f"Testing {filename}"):
                with warnings.catch_warnings():
                    # Avoid warnings from too-long FITS header keys.
                    warnings.simplefilter("ignore", VerifyWarning)
                    self.assertObservationInfoFromYaml(filename, dir=self.datadir, **expected)

    def test_ts8_translator(self):
        test_data = (("ts8-E2V-CCD250-179_lambda_bias_024_6006D_20180724104156.yaml",
                      dict(telescope=None,
                           instrument="LSST-TS8",
                           can_see_sky=False,
                           dark_time=0.0*u.s,
                           detector_exposure_id=201807241041568067,
                           detector_group="RTM-010",
                           detector_name="S11",
                           detector_num=67,
                           detector_serial="E2V-CCD250-179",
                           exposure_id=201807241041568,
                           exposure_group="201807241041568",
                           exposure_time=0.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=24,
                           group_counter_start=24,
                           has_simulated_content=False,
                           observation_counter=24,
                           observation_id="E2V-CCD250-179_lambda_bias_024_6006D_20180724104156",
                           observation_type="bias",
                           observation_reason="lambda",
                           observing_day=20180724,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="y",
                           science_program="6006D",
                           visit_id=201807241041568)),
                     ("ts8-E2V-CCD250-200-Dev_lambda_flat_0700_6006D_20180724102845.yaml",
                      dict(telescope=None,
                           instrument="LSST-TS8",
                           can_see_sky=False,
                           dark_time=21.913*u.s,
                           detector_exposure_id=201807241028453065,
                           detector_group="RTM-010",
                           detector_name="S02",
                           detector_num=65,
                           detector_serial="E2V-CCD250-200",
                           exposure_id=201807241028453,
                           exposure_group="201807241028453",
                           exposure_time=21.913*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=17,
                           group_counter_start=17,
                           has_simulated_content=False,
                           observation_counter=17,
                           observation_id="E2V-CCD250-200-Dev_lambda_flat_0700_6006D_20180724102845",
                           observation_type="flat",
                           observation_reason="lambda",
                           observing_day=20180724,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="z",
                           science_program="6006D",
                           visit_id=201807241028453)),
                     ("ts8-E2V-CCD250-220_fe55_fe55_094_6288_20171215114006.yaml",
                      dict(telescope=None,
                           instrument="LSST-TS8",
                           can_see_sky=False,
                           dark_time=300.0*u.s,
                           detector_exposure_id=201712151140062027,
                           detector_group="RTM-005",
                           detector_name="S00",
                           detector_num=27,
                           detector_serial="E2V-CCD250-220",
                           exposure_id=201712151140062,
                           exposure_group="201712151140062",
                           exposure_time=300.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=94,
                           group_counter_start=94,
                           has_simulated_content=False,
                           observation_counter=94,
                           observation_id="E2V-CCD250-220_fe55_fe55_094_6288_20171215114006",
                           observation_type="fe55",
                           observation_reason="fe55",
                           observing_day=20171215,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="i",
                           science_program="6288",
                           visit_id=201712151140062)),
                     ("ts8-TS_C_20220711_000174_R22_S00.yaml",
                      dict(telescope=None,
                           instrument="LSST-TS8",
                           can_see_sky=False,
                           dark_time=210.315*u.s,
                           detector_exposure_id=202207111714459018,
                           detector_group="RTM-004",
                           detector_name="S00",
                           detector_num=18,
                           detector_serial="ITL-3800C-372",
                           exposure_id=202207111714459,
                           exposure_group="202207111714459",
                           exposure_time=210.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=174,
                           group_counter_start=174,
                           has_simulated_content=False,
                           observation_counter=174,
                           observation_id="TS_C_20220711_000174",
                           observation_type="spot",
                           observation_reason="spot_flat",
                           observing_day=20220711,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="unknown",
                           science_program="7074D",
                           visit_id=202207111714459)),
                     ("ts8-TS_C_20230512_000021_R22_S02.yaml",
                      dict(telescope=None,
                           instrument="LSST-TS8",
                           can_see_sky=False,
                           dark_time=15.165*u.s,
                           detector_exposure_id=202305121917591020,
                           detector_group="RTM-004",
                           detector_name="S02",
                           detector_num=20,
                           detector_serial="ITL-3800C-380",
                           exposure_id=202305121917591,
                           exposure_group="202305121917591",
                           exposure_time=15.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=21,
                           group_counter_start=21,
                           has_simulated_content=False,
                           observation_counter=21,
                           observation_id="TS_C_20230512_000021",
                           observation_type="flat",
                           observation_reason="sflat_hi",
                           observing_day=20230512,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="HIGH",
                           science_program="7187D",
                           visit_id=202305121917591)),
                     ("ts8-TS_C_20230512_000021_R22_S02-fixed.yaml",  # Will not apply header fixups
                      dict(telescope=None,
                           instrument="LSST-TS8",
                           can_see_sky=False,
                           dark_time=15.165*u.s,
                           detector_exposure_id=202305121917591020,
                           detector_group="RTM-004",
                           detector_name="S02",
                           detector_num=20,
                           detector_serial="ITL-3800C-380",
                           exposure_id=202305121917591,
                           exposure_group="202305121917591",
                           exposure_time=15.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=21,
                           group_counter_start=21,
                           has_simulated_content=False,
                           observation_counter=21,
                           observation_id="TS_C_20230512_000021",
                           observation_type="flat",
                           observation_reason="sflat_hi",
                           observing_day=20230512,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="HIGH",
                           science_program="7187D",
                           visit_id=202305121917591)),
                     ("ts8-TS_C_20230523_000127_R22_S00.yaml",
                      dict(telescope=None,
                           instrument="LSST-TS8",
                           can_see_sky=False,
                           dark_time=15.16*u.s,
                           detector_exposure_id=202305231936194018,
                           detector_group="RTM-004",
                           detector_name="S00",
                           detector_num=18,
                           detector_serial="ITL-3800C-372",
                           exposure_id=202305231936194,
                           exposure_group="202305231936194",
                           exposure_time=15.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=127,
                           group_counter_start=127,
                           has_simulated_content=False,
                           observation_counter=127,
                           observation_id="TS_C_20230523_000127",
                           observation_type="flat",
                           observation_reason="flat",
                           observing_day=20230523,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="unknown",
                           science_program="7220D",
                           visit_id=202305231936194)),
                     ("ts8-TS_C_20230525_000041_R22_S00.yaml",
                      dict(telescope=None,
                           instrument="LSST-TS8",
                           can_see_sky=False,
                           dark_time=30.151*u.s,
                           detector_exposure_id=3023052500041018,
                           detector_group="RTM-004",
                           detector_name="S00",
                           detector_num=18,
                           detector_serial="ITL-3800C-372",
                           exposure_id=3023052500041,
                           exposure_group="3023052500041",
                           exposure_time=30.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=41,
                           group_counter_start=41,
                           has_simulated_content=False,
                           observation_counter=41,
                           observation_id="TS_C_20230525_000041",
                           observation_type="flat",
                           observation_reason="flat",
                           observing_day=20230525,
                           observing_day_offset=astropy.time.TimeDelta(28800.0, scale="tai", format="sec"),
                           physical_filter="unknown",
                           science_program="7227D",
                           visit_id=3023052500041)),
                     )
        for filename, expected in test_data:
            with self.subTest(f"Testing {filename}"):
                with warnings.catch_warnings():
                    # Avoid warnings from too-long FITS header keys.
                    warnings.simplefilter("ignore", VerifyWarning)
                    self.assertObservationInfoFromYaml(filename, dir=self.datadir, **expected)

    def test_ucdcam_translator(self):
        test_data = (("UCD-E2V-CCD250-TS_C_20231031_000227_R21_S01.yaml",
                      dict(telescope=None,
                           instrument="LSST-UCDCam",
                           can_see_sky=False,
                           dark_time=2.07859*u.s,
                           detector_exposure_id=42370917130,
                           detector_group="R21",
                           detector_name="S01",
                           detector_num=10,
                           detector_serial="E2V-CCD250-112-09",
                           exposure_id=2023103100227,
                           exposure_group="2023103100227",
                           exposure_time=1.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=227,
                           group_counter_start=227,
                           has_simulated_content=False,
                           observation_counter=227,
                           observation_id="TS_C_20231031_000227",
                           observation_type="flat",
                           observation_reason="flat",
                           observing_day=20231031,
                           observing_day_offset=astropy.time.TimeDelta(0.0, scale="tai", format="sec"),
                           physical_filter="r",
                           science_program="unknown",
                           visit_id=2023103100227)),
                     ("UCD-ITL-3800C-TS_C_20230730_000237_R22_S01.yaml",
                      dict(telescope=None,
                           instrument="LSST-UCDCam",
                           can_see_sky=False,
                           dark_time=3.082*u.s,
                           detector_exposure_id=179029732609,
                           detector_group="R22",
                           detector_name="S01",
                           detector_num=1,
                           detector_serial="ITL-3800C-002",
                           exposure_id=3023073000237,
                           exposure_group="3023073000237",
                           exposure_time=2.0*u.s,
                           focus_z=0.0*u.mm,
                           group_counter_end=237,
                           group_counter_start=237,
                           has_simulated_content=False,
                           observation_counter=237,
                           observation_id="TS_C_20230730_000237",
                           observation_type="flat",
                           observation_reason="flat",
                           observing_day=20230730,
                           observing_day_offset=astropy.time.TimeDelta(0.0, scale="tai", format="sec"),
                           physical_filter="r",
                           science_program="unknown",
                           visit_id=3023073000237)),
                     )
        for filename, expected in test_data:
            with self.subTest(f"Testing {filename}"):
                self.assertObservationInfoFromYaml(filename, dir=self.datadir, **expected)

    def test_checker(self):
        filename = "latiss-future.yaml"
        from astro_metadata_translator.tests import read_test_file
        from astro_metadata_translator import ObservationInfo
        header = read_test_file(filename, self.datadir)
        obsInfo = ObservationInfo(header, pedantic=True, filename=filename)
        self.assertTrue(obsInfo)

    def test_fix_header(self):
        from astro_metadata_translator import fix_header
        from astro_metadata_translator.tests import read_test_file
        # Test that header fix up is working
        # Not all headers are used in metadata translation
        test_data = (
            ("latiss-AT_O_20210212_000006.yaml",
             dict(RASTART=260.024385071917)),
            ("latiss-AT_O_20210210_000011.yaml",
             dict(RASTART=355.41750341182313)),
        )
        for filename, expected in test_data:
            with self.subTest(f"Testing {filename}"):
                header = read_test_file(filename, dir=self.datadir)
                modified = fix_header(header)
                self.assertTrue(modified)
                for k, v in expected.items():
                    self.assertEqual(header[k], v, f"Testing {k} in {filename}")


if __name__ == "__main__":
    unittest.main()
